name: moj-fastapi-skeleton

services:
  db:
    container_name: db
    image: postgres:16
    environment: &database_config
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api
      POSTGRES_PORT: 5432
      POSTGRES_HOST: db
    ports:
      - "5436:5432"
    healthcheck:
      test: pg_isready -U postgres -d api
      start_period: 5s
      start_interval: 0.2s
      interval: 30s
      timeout: 3s
      retries: 3

  api:
    container_name: api
    build:
      context: .
      args:
        REQUIREMENTS: "requirements-development.txt"
    command: uvicorn app:api --host 0.0.0.0 --port 8027 --reload
    ports:
      - "8027:8027"
    environment:
      SECRET_KEY: "TEST_KEY"
      <<: *database_config
    volumes:
      - ./app:/home/app/moj-fastapi-skeleton/app
      - ./tests:/home/app/moj-fastapi-skeleton/tests
    depends_on:
      db:
        condition: service_healthy

  migrations:
    build: .
    container_name: db-migrations
    command: alembic upgrade head
    environment:
      <<: *database_config
    depends_on:
      db:
        condition: service_healthy
